
server:
  port: 8085
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board3
    username: root
    password: test1234
  #  jpa를 사용하기 위한 환경설정
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true

#   mapper파일(mybatis의 실질쿼리파일)의 위치를 명시.
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

#  인코딩된 문자 32자 이상 필요.(특수문자) :base64 encoder
jwt:
  secretKey: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5

